# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 10.x #${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 10.x #${{ matrix.node-version }}


    - name: Installing my packages
      run: npm ci

    - name: Build my App
      run: npm run build
      env:
        APP_NODE_URL: https://eggwaffle-ganache.fly.dev:8545
    - run: touch ./out/.nojekyll

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        BRANCH: my-gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
